### PR TITLE
Add "Website Change Monitor" to the "Open Source" list

### PR DESCRIPTION
**Pull request by JuanmaMenendez**
Issue of reference: https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring/issues/8

### CODE REVIEW

**Comment by Frijol** [comment]
Thanks for the contribution, and sorry to leave it hanging for so long! I just put together contribution guidelines (in PR https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring/pull/10 )– would you please change a couple of style elements in your PR to match?

**Comment by JuanmaMenendez** [comment]
> Thanks for the contribution, and sorry to leave it hanging for so long! I just put together contribution guidelines (in PR [https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring/pull/10)– would](https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring/pull/10)%E2%80%93%C2%A0would) you please change a couple of style elements in your PR to match?

Hello Frijol, your reference link is broken (404)

**Comment by Frijol** [comment]
Urgh. Automatic linking fail, my close-parens broke it. Fixed above now!

**Comment by JuanmaMenendez** [comment]
✔ My PR was already in the correct alphabetical order (coincidentally :P)
✔ I already added the comments in the spreadsheet.

Please tell me if I'm missing something else. Thanks

**Comment by Frijol** [comment]
Yes, please switch to [reference-style](https://www.markdownguide.org/basic-syntax/#reference-style-links) linking.

Thanks for checking things over!

**Comment by JuanmaMenendez** [comment]
It's OK now?

**Comment by Frijol** [comment]
Nearly! It looks like my merged commits to master since your original are showing up in the changed files. Can you rebase your changes onto current master?

**Comment by JuanmaMenendez** [comment]
I will create a new PR

**Pull request closed without merging**
